name: Write message

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Oops! Looks like you found an issue with your code. Thenks for reporting it :^ "
        pr-message: "Hello user! Thank you for contributing to the project! We will review your pull request and make changes according to the same!"
